config/routes.rb
Rails.application.routes.draw do
  get '/auth/spotify/callback', to: 'spotify_auth#callback'
  get '/auth/spotify', to: 'spotify_auth#authenticate'
  mount ActionCable.server => '/cable'

  devise_for :users

  get "welcome/home"

  # get '/users/test', to: 'users#test'
  get "/users/search", to: "users#search", as: :users_search

  get "profile", to: "users#show", as: :user_profile

  resources :users, only: [ :show, :update ]

  namespace :api do
    resources :users, only: [ :update ]
  end

  resources :game_sessions, only: [ :new, :create, :show ] do
    collection do
      post "start_single_player"
      post "start_multiplayer"
    end
    member do
      get "invite"
      post "invite_friend"
      post "start"
      post "accept_invitation"
    end
    resources :rounds, only: [ :create ]
  end

  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  root "welcome#home"
  resources :snippets, only: [ :index, :create, :new ]
  get "fetch_snippets", to: "snippets#fetch_snippets"

  resources :friendships, only: [:index, :create, :update, :destroy]

  get "test", to: "snippets#test"

  post "record_play", to: "user_played_snippets#record_play"
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  before_action :authenticate_user!, except: [ :index, :fetch_snippets ]

  def test
    @lyric_snippet = LyricSnippet.first
  end

  def index
    @game_session = current_game_session
  end

  def new
    @lyric_snippet = LyricSnippet.new
  end

  def create
    @lyric_snippet = LyricSnippet.new(snippet_params)

    if @lyric_snippet.save
      @snippet_data = @lyric_snippet.as_json.merge(
        image_url: @lyric_snippet.image.url
      )
      render :thank_you
    else
      render :new, status: 422
    end
  end

  def fetch_snippets
    user_language = current_user&.language || "English"
    random_ids = LyricSnippet
                .where.not(snippet: "Dummy snippet for failed rounds")
                .where(language: user_language)
                # .where(artist: "Arctic Monkeys")
                .pluck(:id)
                .sample(20)
    snippets = LyricSnippet
                .where(id: random_ids)
                .sample(4)

    render json: snippets.map { |snippet|
      snippet.as_json.merge({
        image_url: snippet.image.attached? ? snippet.image.url : nil
      })
    }
  end

  private

  def snippet_params
    params.require(:lyric_snippet).permit(:snippet, :artist, :song, :difficulty, :language)
  end
end

app/views/snippets/index.html.erb
<div id="main" data-game-session-id="<%= @game_session&.id %>"></div>

app/views/snippets/new.html.erb
<div id="add-snippet-form-wrapper">
  <div id="add-snippet-form-content">
    <h3 class="mb-4 mt-4">Add Lyric Snippet</h3>
    <%= simple_form_for @lyric_snippet, url: snippets_path, data: { turbo: false } do |f| %>
      <%= f.input :snippet, label: false, input_html: { placeholder: "Snippet" } %>
      <%= f.input :artist, label: false, input_html: { placeholder: "Artist" } %>
      <%= f.input :song, label: false, input_html: { placeholder: "Song" } %>
      <%= f.input :language, collection: LyricSnippet.languages, selected: "English", label: false, input_html: { placeholder: "Language" } %>
      <div id="difficulty-slider-container"></div>
      <div class="d-flex justify-content-end">
        <%= f.button :submit, 'Submit', class: "btn btn-accent mt-4" %>
      </div>
    <% end %>
  </div>
</div>

app/views/snippets/test.html.erb
<% if @lyric_snippet.image.attached? %>
  <%= cl_image_tag @lyric_snippet.image.key %>
<% end %>

<h1>--------</h1>

<% if @lyric_snippet.image.attached? %>
  <%= cl_image_tag @lyric_snippet.image.key %>
<% end %>

<h2>jdjaskldasljd</h2>
<h3>qweqwe</h3>

app/views/snippets/thank_you.html.erb
<div class="container" style="margin-top: 6rem">
  <h1 class="text-center">Thanks <%= current_user.name %> 😍</h1>
  <div class="row justify-content-center">
    <div class="col-md-5">
      <div id="snippet-last" data-snippet=
      '<%= raw(@snippet_data.to_json) %>'
      >
      </div>
    </div>
  </div>
</div>