config/routes.rb
Rails.application.routes.draw do
  get '/auth/spotify/callback', to: 'spotify_auth#callback'
  get '/auth/spotify', to: 'spotify_auth#authenticate'
  mount ActionCable.server => '/cable'

  devise_for :users

  get "welcome/home"

  # get '/users/test', to: 'users#test'
  get "/users/search", to: "users#search", as: :users_search

  get "profile", to: "users#show", as: :user_profile

  resources :users, only: [ :show, :update ]

  namespace :api do
    resources :users, only: [ :update ]
  end

  resources :game_sessions, only: [ :new, :create, :show ] do
    collection do
      post "start_single_player"
      post "start_multiplayer"
    end
    member do
      get "invite"
      post "invite_friend"
      post "start"
      post "accept_invitation"
    end
    resources :rounds, only: [ :create ]
  end

  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  root "welcome#home"
  resources :snippets, only: [ :index, :create, :new ]
  get "fetch_snippets", to: "snippets#fetch_snippets"

  resources :friendships, only: [:index, :create, :update, :destroy]

  get "test", to: "snippets#test"

  post "record_play", to: "user_played_snippets#record_play"
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-dark bg-dark fixed-top" style="min-height: 7vh">
  <div class="container-fluid">
    <%= link_to 'SnipSlip', root_path, data: { turbolinks: false }, class: 'navbar-brand' %>

    <div class="position-absolute start-50 translate-middle-x">
      <div class="button-group">
        <% if user_signed_in? %>
          <%= button_to "Play Alone :<",
              start_single_player_game_sessions_path,
              class: "btn me-2 btn-accent",
              method: :post
          %>
          <%= button_to "Play with Friends :>",
              start_multiplayer_game_sessions_path,
              class: "btn btn-accent",
              method: :post
          %>
        <% else %>
          <%= link_to "Play Alone :<",
              new_user_session_path,
              class: "btn me-2 btn-accent"
          %>
          <%= link_to "Play with Friends :>",
              new_user_session_path,
              class: "btn btn-accent"
          %>
        <% end %>
      </div>
    </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <%# off canvas  %>
    <div class="offcanvas offcanvas-end text-bg-dark" style="width: 220px;" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <li class="nav-item">
            <%= link_to 'Add Snippet', new_snippet_path, data: { turbolinks: false }, class: 'nav-link' if user_signed_in? %>
          </li>
          <li class="nav-item">
            <%= link_to "Manage Friends", friendships_path, data: { turbolinks: false }, class: "nav-link" if user_signed_in? %>
          </li>
          <li class="nav-item">
            <div id="invite-friend"></div>
          </li>
          <li class="nav-item">
            <%= link_to 'Profile', user_profile_path, data: { turbolinks: false }, class: 'nav-link' if user_signed_in? %>
          </li>
          <li>
            <% if user_signed_in? %>
              <%= link_to "Logout", destroy_user_session_path,
                data: { "turbo-method": :delete },
                class: "nav-link"
              %>
            <% else %>
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
              <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
            <% end %>
          </li>

        </ul>
      </div>
    </div>
  </div>
</nav>


          <!-- dropdown -->
          <!--
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              More Options
            </a>
            <ul class="dropdown-menu dropdown-menu-dark">
              <li><%= link_to 'Action', '#', class: 'dropdown-item' %></li>
              <li><%= link_to 'Another action', '#', class: 'dropdown-item' %></li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li><%= link_to 'Something else here', '#', class: 'dropdown-item' %></li>
            </ul>
          </li>
          -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "SnipSlip" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css2?family=Caveat:wght@400;600&display=swap", rel: "stylesheet" %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap", rel: "stylesheet" %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css2?family=Gloria+Hallelujah&display=swap", rel: "stylesheet" %>

    <%= stylesheet_link_tag "https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@400;600&display=swap", rel: "stylesheet" %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600&display=swap", rel: "stylesheet" %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css2?family=Quicksand:wght@400;600&display=swap", rel: "stylesheet" %>

    <%= stylesheet_link_tag "https://fonts.googleapis.com/css2?family=Source+Serif+Pro:wght@400;600&display=swap", rel: "stylesheet" %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css2?family=Crimson+Text:wght@400;600&display=swap", rel: "stylesheet" %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;600&display=swap", rel: "stylesheet" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>


  <body data-current-user-id="<%= current_user&.id %>">

    <%= render "layouts/header" %>

    <div class="page-without-header">
      <%= yield %>
    </div>
  </body>

</html>
<!--
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>